### PR TITLE
Fix typo and list object has no attribute 'clear' error

### PR DESCRIPTION
**Pull request by MogiePete**
temp_list.clear() on line 117 results in the application failing with "list object has no attribute 'clear' error". Removing line 117 resolves this error and allows the entire course content to be downloaded.

### CODE REVIEW

**Comment by RahulShaw** [comment]
`list.clear` was introduced in Python 3.3, hence you may like to upgrade your Python version to something higher than that, Python 3.6 won't hurt. Good luck!

**Comment by MogiePete** [comment]
Yea I noticed when it was too late. Removing the list.clear allows it to work with Python 2.7.

Thanks for your work.
